services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
  xss:
    build: ./xss
    env_file:
      - .env
    restart: always
  sqli:
    build: ./sqli
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
  scoreboard:
    build: ./scoreboard
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
  mysql:
    image: mysql:8.0.40
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
  
volumes:
  mysql_data: